version: "3.9"

services:
# брокер сообщений
  redis:
    container_name: redis
#    restart: always
    image: redis


# база данных
  postgres:
      container_name: postgres
      image: postgres
#      restart: always
      env_file:
        - ./app/.env
      environment:
          PGDATA: /var/lib/postgresql/data/db/
      volumes:
        - ./app/postgres:/var/lib/postgresql/data/


# основной сервер
  django:
    container_name: django
    restart: unless-stopped
    build:
      context: app/
    env_file:
      - ./app/.env
    expose:
      - 8000
        #ports:
        #- "8000:8000"
    depends_on:
      - postgres
    volumes:
      - static_data:/server/staticfiles
      - ./app/supervisor/logs/:/var/log

#
  bot:
    container_name: bot
    restart: unless-stopped
    build:
      context: bot/
    command: >
      sh -c "python app.py"
    env_file:
      - ./bot/.env
    volumes:
      - "./bot/logs:/var/log"
    depends_on:
      - django
      - postgres
      - mongodb

# база данных для бота
  mongodb:
    image: mongo:5.0
    container_name: mongodb
    ports:
      - 27017:27017
    env_file:
      - ./bot/.env
    volumes:
      - ./bot/mongo/db/:/data/db

# веб-сервис nginx
  nginx:
    restart: unless-stopped
    image: nginx:latest
    container_name: nginx
    volumes:
      - ./nginx_conf/nginx-conf.d:/etc/nginx/conf.d/default.conf
      - ./nginx_conf/logs/:/etc/nginx/logs/
      - static_data:/server/staticfiles/ 
    ports:
      - "80:80"
    depends_on:
      - django


volumes:
  static_data:
