version: "3.9"

services:
# брокер сообщений
  redis:
    container_name: redis
#    restart: always
    image: redis

# база данных
  postgres:
      container_name: postgres
      image: postgres
#      restart: always
      env_file:
        - ./app/.env
      environment:
          PGDATA: /var/lib/postgresql/data/db/
      volumes:
        - ./app/postgres:/var/lib/postgresql/data/


# основной сервер
  django:
    container_name: django
#    restart: always
    build:
      context: app/
    env_file:
      - ./app/.env
#    expose:
#      - 8000
    ports:
      - "8000:8000"
    depends_on:
      - postgres
    volumes:
      - ./app:/server
      - ./app/supervisor/logs/:/var/log


  bot:
    container_name: bot
    restart: unless-stopped
    build:
      context: bot/
    command: >
      sh -c "python app.py"
    env_file:
      - ./bot/.env
    ports:
      - 8081:8081
    depends_on:
      - django
      - postgres
      - mongodb

# база данных для бота
  mongodb:
    image: mongo:5.0
    ports:
      - 27017:27017
    env_file:
      - ./bot/.env
    volumes:
      - ./bot/mongo:/data/db 

# веб-сервис nginx
#  nginx:
##    restart: always
#    image: nginx:latest
#    container_name: nginx
#    volumes:
#      - ./nginx_conf/nginx.conf:/etc/nginx/nginx.conf
#      - ./nginx_conf/logs/:/etc/nginx/logs/
#      - ./app:/server
#    ports:
#      - "80:80"
#    depends_on:
#      - django
