version: "3.9"

services:
# брокер сообщений
  redis:
    container_name: redis
    restart: always
    image: redis

# база данных
  postgres:
      container_name: postgres
      image: postgres
      env_file:
        - ./app/.env
      environment:
          PGDATA: /var/lib/postgresql/data/db/
      volumes:
        - ./app/postgres:/var/lib/postgresql/data/


# основной сервер
  server:
    container_name: server
    restart: always
    build:
      context: app/
    env_file:
      - ./app/.env
#    ports:
#      - "8000:8000"
    expose:
      - 8000
    command: > 
      sh runscript.sh
    depends_on:
      - postgres
    volumes:
      - static_data:/server/staticfiles

# worker для асинхронной работы и исполнения переодических задач
  worker:
    container_name: celery_worker
    restart: always
    build:
      context: app/
    env_file:
      - ./app/.env
    command: >
      sh -c "celery -A app worker -l INFO"
    depends_on:
      - server

# worker для назначения переодических задач
  celery_beats:
    container_name: celery_beats_worker
    restart: always
    build:
      context: app/
    env_file:
      - ./app/.env
    command: >
      sh -c " celery -A app beat -l INFO
      --scheduler django_celery_beat.schedulers:DatabaseScheduler"
    depends_on:
      - server

# веб-сервис nginx
  nginx:
    restart: always
    image: nginx:latest
    container_name: nginx
    volumes:
      - ./nginx_conf/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx_conf/logs/:/etc/nginx/logs/
      - static_data:/server/staticfiles
    ports:
      - "80:80"
    depends_on:
      - server

volumes:
  postgres:
  static_data:
