# Generated by Django 4.0.7 on 2022-09-24 14:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EventTypeClissifier',
            fields=[
                ('type_code', models.SmallIntegerField(primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='StatusOfEvent',
            fields=[
                ('status_code', models.SmallIntegerField(primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('address', models.CharField(blank=True, max_length=255, null=True)),
                ('start_date', models.DateTimeField(blank=True, null=True)),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('url', models.URLField(max_length=255)),
                ('img', models.URLField(max_length=255)),
                ('status_of_event', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='main.statusofevent')),
                ('type_of_event', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='main.eventtypeclissifier')),
            ],
        ),
    ]
