# Generated by Django 4.0.7 on 2022-11-25 10:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='keyword',
            name='tag_code',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='main.tag'),
        ),
    ]
