# Generated by Django 4.0.7 on 2022-11-28 12:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_keyword_tag_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='type_of_event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.eventtypeclissifier'),
        ),
    ]
